# Document:
# http://simiki.org/docs/configuration.html

url: https://zh.worldmystery.org
title: 世界未解之谜全记录
keywords: 未解之谜, 超自然力量, 神秘学
description: 本站旨在收录全世界范围内的未解之谜的案例，包括：人类之谜、中外名人之谜、军事战争之谜、古文明之谜、考古之谜、历史与地理之谜、动物与植物之谜、自然与科学之谜、宇宙之谜
author: WorldMystery

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

default_ext: md
pygments: false
debug: false
