# Document:
# http://simiki.org/docs/configuration.html

url: https://zh.worldsecrets.net
title: 世界未解之谜全记录
keywords: 未解之谜, 超自然力量, 神秘学
description: 本站旨在收录全世界范围内的未解之谜案例，包括
author: A-Middle-School-Student

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: linux  # 目录名
    label: Linux/运维  # 目录的别名, 生成首页时可以使用
  - name: database
    label: 数据库

default_ext: md
pygments: false
debug: false
